name: GitHub Actions
on: [push]
env:
  APP_IMAGE: keboola/alpine-bash-curl-jq

  DOCKERHUB_USER: "keboolacipush"
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Docker login
        run: docker login --username "$DOCKERHUB_USER" --password "$DOCKERHUB_TOKEN"

      - name: Build image
        run: docker build . -t $APP_IMAGE

      - name: Push Image
        run: docker push $APP_IMAGE
